[#383] Select 컴포넌트
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #385
Opened 2023-07-20 08:56 UTC by minjongbaek

# 구현 내용

* Select 컴포넌트를 구현했어요.

# 스크린샷

# pr 포인트

# Help

* 기본 select 태그로 구현을 하려 했는데, select 아이콘을 변경하지 못해 headless ui의 Listbox 컴포넌트를 이용했어요.
  * 다 만들고나서 보니 모바일 환경에서는 기본 select 태그가 더 편리한 것 같아요. (당근도 기본 select 태그를 사용하는 것 같아요 👀 )
  * **`background: url('/icons/select-icon.svg');` 스타일을 지정했을 때 스토리북에서 제대로 가져오지 못하는 문제가 있는데 혹시 해결 방법을 아시는 분이 있을까요?**

# 관련 이슈

- Close #383

2023-07-23 13:00 UTC, gxxrxn commented
> background: url('/icons/select-icon.svg'); 스타일을 지정했을 때 스토리북에서 제대로 가져오지 못하는 문제가 있는데 혹시 해결 방법을 아시는 분이 있을까요?

storybook 설정파일 `./storybook/main.ts`를 조금 수정하면 해결되는 것 같아요!

[참고](https://storybook.js.org/recipes/tailwindcss/)
아래와 같은 설명이 있어서 참고했습니다!
> 📣 If you are using Vite, @storybook/nextjs, @storybook/angular, or @storybook/preset-create-react-app with react-scripts@2.0.0, then leave the options object empty.

```ts
const config: StorybookConfig = {
  ...,
  staticDirs: ['../public'], // 추가
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    {
      name: '@storybook/addon-styling',
      options: {} // {postCss: true} 제거
    },
  ],
  ...
}
```

2023-07-23 14:40 UTC, gxxrxn reviewed
수고하셨습니다 민종님~!! 코멘트 몇개 남겼는데 확인해주시면 감사하겠습니다! 🙇🏻‍♀️

그리고 혹시 storybook에서 form submit 동작이 잘 되는걸까요? 저는 아래와 같은 에러메시지가 보이고, alert 창이 띄워지지가 않아서요ㅠ.ㅠ

<img width="700" alt="스크린샷 2023-07-23 오후 11 35 30" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/d52e6a8b-331f-4878-81ff-8e7f51956549">

> 다 만들고나서 보니 모바일 환경에서는 기본 select 태그가 더 편리한 것 같아요. (당근도 기본 select 태그를 사용하는 것 같아요 👀 )

모바일 환경과 잘 호환되지 않는다면 기본 select 태그를 활용하면 좋을 것 같아요!!

2023-07-23 14:40 UTC, gxxrxn commented on src/ui/Base/Select.tsx
> +        )}
`Listbox.Options` 컴포넌트에서 `Listbox`의 상태가 open이 아니면 내부적으로 ul 태그를 렌더링하지 않는 것 같아요. 그리고 `div` 태그에 적용된 스타일을 `Listbox.Options`에 줘도 의도한대로 동작할 것 같아요!

`Listbox.Options` 스타일에 `max-height` 속성을 줘서 overflow가 되는 경우 scroll이 되게 하는건 어떨까요? (docs 보고 작성한 코드라 참고만 해주세요!)

이렇게 작성하면 더 간단해질 것 같은데 어떠신가요 민종님?!

```suggestion
        <Listbox.Options className="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-[0.5rem] bg-white py-1 shadow-md focus:outline-none sm:text-sm">
          {children}
        </Listbox.Options>
```

2023-07-23 14:40 UTC, gxxrxn commented on src/ui/Base/Select.tsx
> +const ExportSelect = Object.assign(forwardRef(Select), { Option });
👍🏻

2023-07-23 14:40 UTC, gxxrxn commented on src/ui/Base/Select.tsx
> +  error?: FieldError;
error 타입 때문에 Select가 react-hook-form에 의존적이라는 민종님 말씀 듣고 고민해봤는데, 그럼 해당 컴포넌트에 필요한 `message`만 전달받는 건 어떨까요??

2023-07-24 05:39 UTC, minjongbaek commented on src/ui/Base/Select.tsx
> +  error?: FieldError;
@gxxrxn 오, 좋아요! 아니면 아예 ErrorMessage를 분리시킬 수도 있을 것 같아요. Base 컴포넌트가 다른 Base 컴포넌트에 의존적인게 구조적으로 괜찮은가 싶어서요. 규란님 생각은 어떠신가요?

2023-07-24 05:41 UTC, minjongbaek commented on src/ui/Base/Select.tsx
> +        )}
아 그렇네요 children 으로 조건 렌더링을 하는게 의미가 없군요! 👍 
제안해주신 코드도 괜찮은 것 같아요. 그런데 기본 select 태그를 활용하는 쪽으로 바꿔야 할 것 같아요 ㅎㅎ..

2023-07-24 06:55 UTC, minjongbaek commented
@gxxrxn 기본 select 태그를 활용한 코드로 변경했어요. 확인 부탁드려요!

2023-07-24 07:30 UTC, gxxrxn commented on src/ui/Base/Select.tsx
> +  error?: FieldError;
좋아요!! 👍🏻 아래처럼 에러 아이콘을 포함한 ErrorMessage를 만들어서 Input에서도 사용하면 좋을 것 같아요!! 

<img width="500" alt="스크린샷 2023-07-24 오후 4 28 44" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/a78b6cb0-e809-40e7-810b-007451340510">

2023-07-24 07:48 UTC, gxxrxn requested changes

2023-07-24 07:48 UTC, gxxrxn commented on src/ui/Base/Select.tsx
> +    'className' | 'defaultValue' | 'requirder'
오타발견..😛

```suggestion
    'className' | 'defaultValue' | 'required'
```

2023-07-24 07:57 UTC, minjongbaek commented on src/ui/Base/Select.tsx
> +  error?: FieldError;
그럼 이건 다음 PR에서 처리하도록 하겠습니당

2023-07-26 01:24 UTC, WooDaeHyun approved these changes
민종님 고생하셨습니다! 👍 

아래 코멘트는 select 태그 활용 코드로 변경 전에 review를 남겼는데 submit을 안 하고 pending 상태로 있었던 질문이었습니다! 지금은 Select, Option 컴포넌트의 props 타입이 모두 바뀌어 있어서,, 혹시 해당 부분 기억이 나신다면 알려주신다면 감사하겠습니다 ㅎㅎㅎ

2023-07-26 01:28 UTC, minjongbaek commented on src/ui/Base/Select.tsx
> +  children: ReactNode;
이것은 저의 실수입니다 ㅎㅎ,, 🥲

2023-07-26 07:59 UTC, hanyugeon approved these changes
수고하셨습니다!!

2023-07-26 07:59 UTC, hanyugeon commented on src/ui/Base/Select.tsx
> +        className={`rounded-[0.5rem] border-[0.05rem] px-[1.0rem] py-[1.3rem] outline-none ${borderColor} cursor-pointer appearance-none bg-[url('/icons/select-icon.svg')] bg-[calc(100%-1rem)_center]
comment;

bg-[calc(100%-1rem)_center]와 같은 클래스로 background-position 속성을 추가할수도 있군요!?
👍

2023-07-26 07:59 UTC, hanyugeon commented on src/ui/Base/Select.tsx
> +const ExportSelect = Object.assign(forwardRef(Select), { Option });
comment;

와우 이거 신기한데요? 배워갑니다 🙇

2023-07-27 13:26 UTC, minjongbaek commented on src/ui/Base/Select.tsx
> +        className={`rounded-[0.5rem] border-[0.05rem] px-[1.0rem] py-[1.3rem] outline-none ${borderColor} cursor-pointer appearance-none bg-[url('/icons/select-icon.svg')] bg-[calc(100%-1rem)_center]
`[]`를 통해 대부분의 스타일이 가능하더라구요 ㅎㅎ..!

2023-07-27 13:27 UTC, merged