[#367] Switch 컴포넌트
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #386
Opened 2023-07-24 01:53 UTC by gxxrxn

# 구현 내용
Switch 컴포넌트 구현했습니다.

# 스크린샷
![switch](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/aa0e2650-384e-4829-938f-1855270af4f2)

# 관련 이슈

- Close #367

2023-07-24 02:26 UTC, minjongbaek commented on src/stories/Base/Switch.stories.tsx
> +  };
just ask;
실제 핸들러를 통해 받는 comment는 string 타입인가요? boolean 타입인가요?
체크가 되어있지 않으면 빈 문자열이 넘어온다고 하셨었나요?

2023-07-24 06:44 UTC, minjongbaek requested changes
같이 작업한 내용이라 코멘트할 내용이 많지 않네요. SwitchWithUseForm 스토리에서 defaultValues의 타입만 변경해주시면 될 것 같아요!

2023-07-24 06:44 UTC, minjongbaek commented on src/stories/Base/Switch.stories.tsx
> +    defaultValues: { comment: 'true' },
comment의 타입이 boolean 이어야 할 것 같아요. 처음은 defaultValue가 'true' 지만 스위치가 토글 되면 boolean 값으로 변환되고 있어요!

2023-07-24 07:55 UTC, WooDaeHyun reviewed
LGTM!! 고생하셨습니다~!

2023-07-24 08:09 UTC, minjongbaek approved these changes
👍

2023-07-26 01:12 UTC, WooDaeHyun approved these changes
👍

2023-07-27 11:07 UTC, hanyugeon reviewed
고생하셧씁니다!!

2023-07-27 11:07 UTC, hanyugeon commented on src/ui/Base/Switch.tsx
> +  ref: Ref<HTMLInputElement>
ask;

잘 몰라서 질문합니다...!

`Omit<componentPropsWithoutRef<'input'>, 'id' | 'type' | 'className'>`
해당 구문은 input의 `ref`, `id`, `type`, `className` props를 제외한 타입으로 이해했는데
어떻게 하단 JSX구문에 있는 `<input>` 에서 타입에러가 나지 않는거죠? 👀

2023-07-27 11:07 UTC, hanyugeon commented on src/ui/Base/Switch.tsx
> +export default forwardRef(Switch);
just ask;

form과 ref를 활용한 컴포넌트 작성은 참 어려운것 같습니다 😭 
많이 공부해야겠어요...!

고생하셨습니다!!!

2023-07-27 14:55 UTC, gxxrxn commented on src/ui/Base/Switch.tsx
> +  ref: Ref<HTMLInputElement>
제가 `Omit<componentPropsWithoutRef<'input'>, 'id' | 'type' | 'className'>` 이렇게 type을 지정했던 이유는 input에서 사용할 수 있는 props들은 모두 Switch 컴포넌트의 props로 제공하지만, id, type, className 프로퍼티는 외부에서 제어할 수 없고 컴포넌트 내부에서 지정해서 전달하겠다는 의미였습니다!

애초에 input에 전달할 수 있는 prop들이 모두 옵셔널해서 해당 값들을 넘겨주지 않는다고 해서 타입 오류가 발생하지도 않을 뿐더러, 아래 jsx 구문에서는 input에게 각 prop 타입에 맞는 적절한 값을 넘겨주고 있으니 더욱이 타입 오류가 발생할 일은 없을 것 같아요!!

혹시 여전히 이해가 안되신다면 다시 코멘트 남겨주세요! 🙂🙏🏻

2023-07-27 14:59 UTC, hanyugeon approved these changes

2023-07-27 15:12 UTC, merged