[#362] TopNavigation 컴포넌트 리팩터링
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #393
Opened 2023-08-13 09:02 UTC by minjongbaek

# 구현 내용

* `TopNavigation` 컴포넌트와 Post/Edit 컴포넌트의 디자인이 유사하여 `TopNavigation` 컴포넌트를 재사용 가능하게끔 리팩터링했어요.
* `TopNavigation`은 큰 틀만 제공하고, 안에 들어갈 요소는 `TopNavigation` 컴포넌트의 `Left/Center/RightItem` 컴포넌트를 통해 UI를 구성할 수 있어요.

# 스크린샷

# pr 포인트

# Help

@gxxrxn TopNavigation 컴포넌트에서 사용될 border가 없는 `Button` 컴포넌트도 필요할 것 같아요.

<img width="419" alt="Screenshot 2023-08-13 at 6 00 08 PM" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/4fba23bb-4d89-4ee2-bafd-cdccdcd72c3f">

# 관련 이슈

- Close #362 #358

2023-08-13 10:25 UTC, hanyugeon reviewed
코멘트 확인해주세요!

확실히 확장성과 재사용성 측면에서 아주 좋아진것 같습니다 😃 💯

2023-08-13 10:25 UTC, hanyugeon commented on src/ui/Base/TopNavigation.tsx
> +    <div className="relative flex w-full items-center justify-center bg-opacity-0 px-[2rem] py-[1.7rem] text-md">
p1;

`height` 값이 빠져서 ItemCenter 컴포넌트를 사용하지 않을때는 TopNavigation 컴포넌트의 높이값이 제대로 나오지 않는것 같습니다!!

ItemCenter 있을 때
<img width="662" alt="Screen Shot 2023-08-13 at 6 58 34 PM" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/55b60363-ce4f-4ad7-92e5-f99174d7066a">

ItermCetner 없을 때
<img width="664" alt="Screen Shot 2023-08-13 at 6 59 43 PM" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/41bbaafd-1255-491d-9c93-58e67af3e13c">

2023-08-13 14:45 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className="relative flex w-full items-center justify-center bg-opacity-0 px-[2rem] py-[1.7rem] text-md">
@hanyugeon [eb005da](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/393/commits/eb005da06f2f955b1574df5ea08be4eb3e5f4d7a) 수정했습니다~

2023-08-14 01:12 UTC, hanyugeon approved these changes
좋아요~ 고생하셨습니다 💯

2023-08-15 08:56 UTC, WooDaeHyun approved these changes
휴가를 다녀오느라 좀 늦었습니다! 
고생하셨습니다. 👍

2023-08-16 10:22 UTC, gxxrxn requested changes
수고하셨습니다!! 재현님 말씀처럼 확장해서 사용하기 좋은 코드가 되었네용! 코멘트 한번만 확인해주세요!

2023-08-16 10:22 UTC, gxxrxn commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
text-overflow 될 경우를 대비해서 `truncate` 클래스 추가하면 좋을 것 같아요! [(참고)](https://tailwindcss.com/docs/text-overflow#truncate)

```suggestion
    <div className={`w-full px-[3.5rem] truncate ${alignClassName}`}>{children}</div>
```

2023-08-16 11:05 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
오 좋네요, 그런데 텍스트를 일부분만 보여주는게 UX 관점에서 좋은지는 모르겠어요.

가령 상세페이지 같은 곳에서 해당 컴포넌트가 쓰일 수 있을 것 같은데, 상세 페이지인데 내용의 일부분이 잘리면 사용자는 어디서 전체 내용을 봐야할까요? 🤔

2023-08-16 11:05 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@gxxrxn 오 좋네요, 그런데 텍스트를 일부분만 보여주는게 UX 관점에서 좋은지는 모르겠어요.

가령 상세페이지 같은 곳에서 해당 컴포넌트가 쓰일 수 있을 것 같은데, 상세 페이지인데 내용의 일부분이 잘리면 사용자는 어디서 전체 내용을 봐야할까요? 🤔

2023-08-16 11:14 UTC, gxxrxn commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@minjongbaek 메인 컨텐츠를 보여주는 영역에서 텍스트 전체를 보여주면 좋지 않을까요?! 상단 네비게이션에서 2줄 이상의 텍스트를 보여주기엔 한계가 있을 것 같고, 잘리는게 싫다면 텍스트가 rolling 되도록 구현해볼 수 있을 것 같아요!

2023-08-16 11:18 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@gxxrxn 다른 서비스를 보니 콘텐츠를 보여주는 페이지에서는 GNB에 아무런 텍스트를 넣어주지 않는 방법도 있을 것 같아요 ![image](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/0412ad62-4243-4dcf-b059-b9bc1f0a040a)

2023-08-18 08:20 UTC, gxxrxn commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@minjongbaek @hanyugeon 
고민해보니 제가 참고했던 서비스는 타이틀이 상대적으로 중요했기 때문에 GNB 영역에서 보여줬던 것 같아요!(밴드 모임 쪽 UI를 참고했습니다!) 민종님 말씀처럼 텍스트 없이 GNB를 구성하는 것도 좋아 보입니다!! 재현님 생각은 어떠신가요?!

2023-08-18 09:16 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
피그마 기준으로 글 작성하기 처럼 새로운 레이어가 생기는 경우에는 보여주면 좋을 것 같아요! 아래 사진처럼요!

![image](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/d6881c09-a3df-4516-be43-236be86f5d87)

2023-08-18 09:37 UTC, gxxrxn commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
책 이름, 모임 이름 등의 타이틀을 보여주는 상세 페이지에서는 제거하고, 글 작성 / 댓글 수정을 위한 레이아웃에서는 보여주자는 말씀이시죠?

2023-08-18 09:41 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@gxxrxn 네 맞아요! 일관성이 없어 보일 수는 있지만, 폼, 키보드, 액션 버튼만 있는 UI에서는 텍스트를 보여주는게 좋을 것 같다고 생각해요.

2023-08-18 09:53 UTC, gxxrxn commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
좋습니다~

2023-08-18 09:53 UTC, gxxrxn approved these changes

2023-08-18 13:38 UTC, hanyugeon commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
comment;

@minjongbaek @gxxrxn 
`그런데 텍스트를 일부분만 보여주는게 UX 관점에서 좋은지는 모르겠어요.` 이 부분에 동감합니다!
피그마 디자인을 확인해보니 책 이름, 모임 이름, 유저 프로필, 등... GNB에 타이틀은 빠져도 좋을 것 같네요!!

2023-08-18 13:58 UTC, minjongbaek commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@hanyugeon @gxxrxn 그럼 이대로 머지하겠습니다~

2023-08-18 14:02 UTC, hanyugeon commented on src/ui/Base/TopNavigation.tsx
> +    <div className={`w-full px-[3.5rem] ${alignClassName}`}>{children}</div>
@minjongbaek 네넵

2023-08-18 14:08 UTC, merged