[#404][독서모임] 모임 검색 컴포넌트
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #419
Opened 2023-10-16 15:03 UTC by WooDaeHyun

# 구현 내용

- 모임 검색창 컴포넌트 구현
- event handler는 외부에서 주입하도록 구현

# 스크린샷

![스크린샷 2023-10-17 오전 12 00 08](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/113018070/b0e8a652-d0fd-4654-b88f-80636bca1fc2)

# pr 포인트

- width는 full로 작성
- 현재 검색을 위한 api가 존재하지 않아 추후 `toast`를 사용하여 기능을 사용할 수 없음을 안내해 줄 예정입니다. (storybook은 현재 toast가 merge되지 않아 alert로 구현했습니다.)

# Help

# 관련 이슈

- Close #404

2023-10-17 01:19 UTC, minjongbaek requested changes

2023-10-17 01:19 UTC, minjongbaek commented on src/ui/Base/FloatingButton.tsx
> +}
postion을 'left-top' 처럼 fullName으로 작성하는건 어떠신가요? 조금 길더라도 단번에 파악 가능하면 좋을 것 같아요.

만약 약어로 사용하고자 한다면, tailwind 에서 제공하는 포맷과 동일하게 t, b가 먼저 나오면 좋을 것 같아요. (ex. tl, br)

2023-10-17 01:19 UTC, minjongbaek commented on src/ui/Base/bookgroup/SearchGroup.tsx
> +        className="placeholder:text-Placeholder h-[3.7rem] w-full rounded-br-[0.4rem] rounded-tr-[0.4rem] border-[0.1rem] border-l-[0rem] border-black-100 pl-[2rem] text-[1.4rem] leading-[1.6rem] foc
오타가 있어요!

```suggestion
        className="placeholder:text-placeholder h-[3.7rem] w-full rounded-br-[0.4rem] rounded-tr-[0.4rem] border-[0.1rem] border-l-[0rem] border-black-100 pl-[2rem] text-[1.4rem] leading-[1.6rem] focus:outline-0"
```

2023-10-18 15:32 UTC, WooDaeHyun commented
@minjongbaek @gxxrxn @hanyugeon

2023-10-18 15:45 UTC, minjongbaek commented on src/ui/Base/FloatingButton.tsx
> +}
이건 아직 푸시가 안된건가요? 👀

2023-10-18 16:16 UTC, minjongbaek commented on src/ui/Base/FloatingButton.tsx
> +}
@WooDaeHyun 해당 내용은 아직 push가 안됐는데 다음 PR을 말씀하신 걸까요?

2023-10-19 14:26 UTC, WooDaeHyun commented on src/ui/Base/FloatingButton.tsx
> +}
@minjongbaek @hanyugeon 네 아직 수정하지 않았어요 comment에 이름 태그하는것을 깜빡해서 제가 한 작업들에 전부 달아 놓다보니 헷갈리게 만들었던것 같습니다. 작업 후에 다시 태그 하도록 하겠습니다. 죄송합니다~

2023-10-19 15:22 UTC, WooDaeHyun commented on src/ui/Base/FloatingButton.tsx
> +}
@hanyugeon @minjongbaek 해당 부분 좋은 의견인것 같아 fullName으로 작성하면서 tailwind 순서에 맞게 변경했습니다.
해당 내용 floating 버튼 컴포넌트 이야기이지만 해당 작업내용이 모임 검색 컴포넌트에도 같이 올라와있고 리뷰도 이곳에 작성되었으니, 이곳에서 수정내용 말씀드립니다.

그 외 모임 검색 컴포넌트에서도 handler라는 이벤트 핸들러 명칭대신 명확하게 변경했습니다. 
감사합니다~!

2023-10-23 15:03 UTC, minjongbaek approved these changes

2023-10-30 11:21 UTC, gxxrxn approved these changes
수고하셨습니다~!!

2023-10-31 09:46 UTC, hanyugeon reviewed
코멘트 확인해주세요!

2023-10-31 09:46 UTC, hanyugeon commented on src/ui/Base/bookgroup/SearchGroup.tsx
> +        className="placeholder:text-Placeholder h-[3.7rem] w-full rounded-br-[0.4rem] rounded-tr-[0.4rem] border-[0.1rem] border-l-[0rem] border-black-100 pl-[2rem] text-[1.4rem] leading-[1.6rem] foc
```suggestion
        className="placeholder:text-placeholder h-[3.7rem] w-full rounded-br-[0.4rem] rounded-tr-[0.4rem] border-[0.1rem] border-l-[0rem] border-black-100 pl-[2rem] text-[1.4rem] leading-[1.6rem] focus:outline-0"
```

placeholder:text-placeholder 이부분이 아직 수정되지 않은 것 같아요!

2023-11-04 09:00 UTC, merged