[#414] [프로필] 프로필 수정 페이지
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #426
Opened 2023-10-21 11:48 UTC by hanyugeon

# 구현 내용

# 스크린샷

# pr 포인트
`TopNavigation`의 position 속성을 수정하였습니다.
`InputLength` 내부 컴포넌트를 분리하고싶은데 기가막힐 방법이 떠오르질 않네요
러프하게 작성된 코드라 가독성이 쓰레기 ~~일 수 있습니다.~~ 입니다. (주석을 추가해 두었습니다...!)

# Help
`InputLength` 컴포넌트를 분리하고 싶어요.

# 관련 이슈

- Close #414

2023-10-30 06:54 UTC, gxxrxn reviewed
> InputLength 컴포넌트를 분리하고 싶어요.

@hanyugeon 
코드가 FormValues 타입에 의존하고 있어서 분리가 어렵다는 뜻으로 이해했는데 맞을까요??

확인해보니 `UseControllerProps`를 통해 control과 name props를 가져와야 타입이 일치하는 것 같아요.

```ts
type InputLengthProps<
  TFieldValues extends FieldValues = FieldValues,
  TFieldName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>
> = Pick<UseControllerProps<TFieldValues, TFieldName>, 'control' | 'name'> & {
  minLength: number;
  maxLength: number;
};
```

그리고 InputLength 컴포넌트에서 제네릭을 받아 전달해주면 FormValues 타입에 의존적이지 않은 컴포넌트를 만들 수 있을 것 같아요!

```tsx
const InputLength = <T extends FieldValues>({
  control,
  name,
  minLength,
  maxLength,
}: InputLengthProps<T>) => {
  // ...
};
```
확인해보고 코멘트 남겨주세요~!!

2023-11-11 09:45 UTC, hanyugeon reviewed
@minjongbaek @WooDaeHyun @gxxrxn 

리뷰해주셔도 좋습니다

2023-11-12 07:33 UTC, minjongbaek requested changes

2023-11-12 07:33 UTC, minjongbaek commented on src/app/profile/me/edit/page.tsx
> + */
ask;
`<Suspense />` 가 이미 사용되고 있는 것으로 보이는데 fallback UI를 추가해야 한다는 말씀이신가요?

2023-11-12 07:33 UTC, minjongbaek commented on src/stories/Base/InputLength.stories.tsx
> +};
p2;
Default Story가 너무 많은 기능을 포함하고 있는 것 같아요.
hookForm과 분리해서 Input 하나만 보여주는걸 Default Story로 두고 hookForm과 사용가능한 Story를 따로 만들어주는건 어떨까요?

2023-11-12 07:33 UTC, minjongbaek commented on src/ui/Base/InputLength.tsx
> +  });
p2;
컴포넌트 내부에서 `useWatch()` 를 사용하면서 react hookform에 의존하는 컴포넌트가 된 것 같아요. `InputLength` 는 결국 Input 요소에 몇 글자가 입력되었는지를 나타내는 역할만 수행하면 되니까, 보여줄 정보를 prop으로 받는건 어떨까요?

2023-11-12 07:33 UTC, minjongbaek commented on src/v1/profile/EditMyProfile.tsx
> +              )}
p2;

이 구조를 보고 InputLegnth 컴포넌트가 왜 hook-form 에 종속적인 컴포넌트가 되었는지 대략적으로 알 수 있었던 것 같아요.

제가 보기에는 Input 컴포넌트에 register 로 ref 를 넘겨주기 때문에  `control` 로 Input에 입력된 데이터의 길이를 가져오는 것으로 보여요.

[`<Controller />`](https://www.react-hook-form.com/api/usecontroller/controller/)를 사용한다면 InputLength 컴포넌트를 react-hook-form 에 종속적이지 않은 컴포넌트로 변경할 수 있을 것 같아요!

2023-11-13 09:01 UTC, hanyugeon commented on src/app/profile/me/edit/page.tsx
> + */
넵 맞습니다 suspense보다는 fallback ui가 맞는 말이겠군요!

2023-11-14 14:16 UTC, hanyugeon commented on src/v1/profile/EditMyProfile.tsx
> +              )}
comment; @minjongbaek 

react-hook-form에 종속되지 않도록 수정해보았습니다!
[bd2b45e](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/426/commits/bd2b45e9a4c3612293dacd22b5b480945bb6d15f)

2023-11-14 15:16 UTC, minjongbaek approved these changes

2023-11-14 15:16 UTC, minjongbaek commented on src/v1/profile/EditProfile.tsx
> +const EditMyProfile = ({ profile, jobGroups }: UserProfileProps) => {
p5;
파일명과 export default 되는 컴포넌트의 이름이 같으면 좋을 것 같아요. 지금은 괜찮지만 한 파일에서 여러 컴포넌트를 선언하는 경우 컴포넌트를 쉽게 찾을 수 있을 것 같아서요.

2023-11-14 15:16 UTC, minjongbaek commented on src/ui/Base/InputLength.tsx
> +  const currentLength = currentValue ? currentValue.length : 0;
p5;
input value를 받지 않고 length를 바로 받아도 괜찮을 것 같네요!

2023-11-14 17:05 UTC, WooDaeHyun reviewed
comment 확인 부탁드립니다~ 👍

2023-11-14 17:05 UTC, WooDaeHyun commented on src/v1/profile/EditProfile.tsx
> +          />
ask;
단순히 IconClose가 close만을 위한 것이라면 router.push 대신 Link 태그로 감싸는건 어떻게 생각하시나요?
해당 부분에 대한 의문이 생겨 router와 Link태그의 차이점들을 검색하면서 알게 되었는데 두 라우팅 방식에 있어서 엄청난 차이가 존재하지는 않지만 가장 큰 차이는 아무래도 SEO 측면에서 차이가 있다는 글들이 많이 있네요! 아무래도 a태그를 활용하는가 하지 않는가에서 오는 차이점인 것 같습니다. 

다음 글들은 제가 읽어 본 글들이니 한 번 참고해 주시면 좋을 것 같아요~
[Link vs router](https://imagineu.tistory.com/83)
[Link vs router vs a태그](https://velog.io/@e_juhee/a-vs-Link-vs-router.push-%EC%B0%A8%EC%9D%B4%EC%A0%90-%EB%B9%84%EA%B5%90)

2023-11-16 10:24 UTC, hanyugeon commented on src/v1/profile/EditProfile.tsx
> +const EditMyProfile = ({ profile, jobGroups }: UserProfileProps) => {
@minjongbaek 

제가 놓친 부분이네요! 수정하였습니다! [191e9f9](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/426/commits/191e9f9604e94f823bbfd1913f929769fdcca3ef) 👍

2023-11-16 10:27 UTC, hanyugeon commented on src/ui/Base/InputLength.tsx
> +  const currentLength = currentValue ? currentValue.length : 0;
@minjongbaek 

민종님 의견을 듣고 이전의 currentValue props가 컴포넌트의 역할과는 일관성이 떨어진다고 판단하여
currentValue > currentLength로 수정하였습니다! [c51289a](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/426/commits/c51289ae5f5fba5fdb43cb374c0448763f79d4e1) 👍

2023-11-16 10:28 UTC, hanyugeon reviewed
@minjongbaek @WooDaeHyun @gxxrxn 

다시 리뷰해주셔도 좋습니다

2023-11-16 15:41 UTC, minjongbaek approved these changes
👍

2023-11-18 16:09 UTC, WooDaeHyun approved these changes
고생하셨습니당! 👍

2023-11-18 17:15 UTC, merged