[#415]  [프로필] 프로필 생성 페이지 (WIP)
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #427
Opened 2023-10-21 12:19 UTC by hanyugeon

# 구현 내용
프로필 생성 페이지를 구현하였습니다

# 스크린샷

# pr 포인트
아직 TopNavigation, Storybook, Tailwind.Config에 수정한 내용이 머지되지않아 **최종 완성본이 아닙니다!!**

폼 부분은 `프로필 수정 페이지`와 똑같습니다.

`프로필 수정 페이지`와 코드가 다른 부분은
상단 글귀가 작성되면서 이를 감싸주는 컨테이너 추가된 부분 입니다.

# Help

# 관련 이슈

- Close #415

2023-11-20 18:25 UTC, hanyugeon commented
@gxxrxn @minjongbaek @WooDaeHyun

리뷰해주셔도 좋습니다!

2023-11-22 06:36 UTC, minjongbaek approved these changes
👍 👍 👍

2023-11-22 06:36 UTC, minjongbaek commented on src/v1/profile/CreateProfile.tsx
> +            showToastEditFailed();
👍 👍 👍 나중에 시간 여유가 됐을 때 범용적인 에러 핸들링이 가능하게끔 수정해봐도 좋을 것 같아요.

2023-11-22 06:36 UTC, minjongbaek commented on src/v1/profile/CreateProfile.tsx
> +const CreateProfile = ({ jobGroups }: UserProfileProps) => {
p5;

@hanyugeon 회원가입 이후 직군 정보를 등록하는 프로세스에 사용되는 컴포넌트니까 이름을 조금 더 명확하게 해주면 좋을 것 같아요! 추후 회원가입 폼 컴포넌트와 헷갈릴 수도 있지 않을까 싶어서요.

2023-11-22 06:36 UTC, minjongbaek commented on src/v1/profile/CreateProfile.tsx
> +      message: '회원 가입 완료!',
p4;

위에 남긴 코멘트와 비슷한 맥락이에요. 회원가입 이후에 진행되는 프로세스니까 `프로필 등록 완료!` 와 같은 메시지로 교체해도 좋을 것 같아요.

2023-11-23 08:45 UTC, gxxrxn requested changes
수고하셨습니다!! 👍🏻 코멘트 몇 개 남겼어요. 확인 부탁드려요! 🙇🏻‍♀️

2023-11-23 08:45 UTC, gxxrxn commented on src/app/profile/me/add/page.tsx
> +  const allJobQuery = useAllJobQuery({ enabled: isAuthed() });
p1;

직군/직업 카테고리 데이터는 거의 변경될 일이 없으니 query option에서`staleTime: Infinity`로 설정하면 어떨까요? 그리고 `useAllJobQuery`의 query key도 분리해서 관리하면 좋을 것 같아요!

이런 형태면 어떨까요? 더 나은 구조가 있다면 그렇게 반영해주셔도 좋아요!

```ts
/** src/queries/job/key.ts */
const jobKeys = {
  all: ['job'] as const,
  category: () => [...jobKeys.all, 'category'] as const,
};

export default jobKeys;
```
```ts
const useAllJobQuery = (options?: Options) =>
  useQuery(
    jobKeys.category(),
    () => jobAPI.getAllJobs().then(response => response.data),
    { ...options, staleTime: Infinity }
  );
```

2023-11-23 08:45 UTC, gxxrxn commented on src/v1/profile/CreateProfile.tsx
> +const CreateProfile = ({ jobGroups }: UserProfileProps) => {
흐음~ `AddJob`..?

2023-11-23 08:45 UTC, gxxrxn commented on src/v1/profile/CreateProfile.tsx
> +      message: '회원 가입 완료!',
`프로필을 등록했어요!` 는 어떤가요!?

2023-11-23 08:45 UTC, gxxrxn commented on src/v1/profile/CreateProfile.tsx
> +  jobGroups: APIJobGroup[];
p2;

개인적으로는 `UserProfileProps` 라는 네이밍이 어색해보여요. 범용적으로 사용되는 사용자 프로필에는 직군/직업 카테고리 정보가 아닌 다른 정보들이 포함되어 있는데, 이와 혼동될 수 있을 것 같아요. `jobGroups` prop은 API 명세의 key 값을 그대로 사용한걸까요? 그렇다면 `APIAllJob` 타입과 형태가 똑같아 보여서 이를 재사용하면 좋을 것 같아요! 하지만 저는 `CreateProfile` 컴포넌트가 필요한 정보를 명시적으로 prop으로 받으면 좋을 것 같아요.

이런 형태는 어떨까요??

```ts
type CreateProfileProps {
  jobCategories: APIJobGroup[];
}
```

2023-11-23 09:55 UTC, WooDaeHyun submitted a review, later dismissed
고생하셨습니다~! 👍

2023-11-25 07:47 UTC, hanyugeon commented on src/app/profile/me/add/page.tsx
> +  const allJobQuery = useAllJobQuery({ enabled: isAuthed() });
@gxxrxn 

이게 이전에 말했던 [쿼리 키 팩토리](https://tkdodo.eu/blog/effective-react-query-keys#use-query-key-factories) 패턴인가 보군요!!
규란님이 작성해주신 예시와 아티클 참고해서 잘 적용해보도록 하겠습니다.
감사합니다~~ 👍

2023-11-26 12:24 UTC, gxxrxn approved these changes
👍🏻

2023-11-27 06:00 UTC, minjongbaek approved these changes
👍

2023-11-29 09:42 UTC, merged