[#435] [북카이브] 북카이브 페이지 (회원)
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #436
Opened 2023-11-09 15:17 UTC by minjongbaek

# 구현 내용

* 북카이브 페이지 (회원) 을 디자인에 맞게 수정했어요.
* 북카이브 페이지에 있던 Chakra UI를 전부 걷어냈어요.
* `v1/bookShelf` 에 위치한 `BookShelf` 컴포넌트 이름을 `BookShelfCard` 로 교체했어요.

# 스크린샷

![image](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/148c2580-9ce4-411d-8fdb-3cacbefc614d)

# pr 포인트

* 책을 추천하는 UI는 북카이브 페이지에서만 노출되고 있어 컴포넌트로 만들지 않았어요.

# 관련 이슈

- Close #435

2023-11-09 15:31 UTC, minjongbaek commented on src/v1/book/BookCover.tsx
> +    <div className={`relative ${sizeClasses}`}>
@gxxrxn 기존 코드에는 감싸는 요소가 `<span />` 태그로 작성되어 있었는데 inline 요소를 사용하신 이유가 있을까요?

BookCover 컴포넌트가 display:inline 이기 때문에 사용하는 곳에서 크기를 명시적으로 정해줘야하는 문제가 있어서 `<div />` 태그로 수정해두었어요. 👀

2023-11-11 08:54 UTC, hanyugeon reviewed
@minjongbaek

고생하셨습니다!
코멘트 확인해주세요~

+a) #412 #435 두 가지 이슈가 중복되고있습니다 확인해주세요!

2023-11-11 08:54 UTC, hanyugeon commented on src/v1/bookArchive/BookArchiveForAuth.tsx
> +          </div>
p5;

key값만 부여받는 역할의 `<div />` 요소라면 [Fragments](https://react.dev/reference/react/Fragment)를 활용해 보아도 좋을 것 같습니다!

2023-11-11 08:54 UTC, hanyugeon commented on src/v1/bookShelf/BookShelfCard.tsx
> +}: APIBookshelf) => {
comment;

현재 `BookShelfCard` 컴포넌트에  `BookShelf`, `Book` 컴포넌트가 한꺼번에 정의되어 사용되고 있습니다!

이후 `북카이브` 뿐만이 아닌 `사용자 책장 페이지`, `프로필 페이지`에서도 사용하기 용이한 구조를 만들 수 있도록 고민해보아도 좋을 것 같아요!

마크업 및 API연동은 잘 구현해 주신것같아요! 고생하셨어요!!

2023-11-12 03:00 UTC, minjongbaek commented on src/v1/bookArchive/BookArchiveForAuth.tsx
> +          </div>
@hanyugeon 해당 div 요소는 key 역할 뿐 아니라 BookCover 와 title을 수직으로 배치하기 위한 역할도 수행하고 있어요. Fragments를 사용하게되면 트리의 계층 구조가 허물어져 레이아웃이 틀어질거에요.

2023-11-12 03:32 UTC, minjongbaek commented on src/app/bookarchive/page.tsx
> +    </div>
@hanyugeon 혹시 이 부분이 오늘 스크럼 때 이야기 했던 내용과 연결되는 건가요?

2023-11-12 03:39 UTC, minjongbaek commented on src/v1/bookShelf/BookShelfCard.tsx
> +}: APIBookshelf) => {
@hanyugeon 재현님 의견에 동의해요. 북카이브와 책장 페이지에서 보여지는 모습이 미세하게 달라서 어떻게 추상화를 할 지 고민하다가 우선 작업 목적에 맞게끔 구현해두었어요.
다음 책장 페이지를 작업하게 된다면 의견 반영하도록 하겠습니다~

2023-11-14 14:21 UTC, hanyugeon commented on src/app/bookarchive/page.tsx
> +    </div>
@minjongbaek

>ContextProvider 에서 사용되는 Layout 컴포넌트가 교체되어야 한다는 말씀이신가요? 👀

다시 검토해보니 아직 BottomNavigation에 BottomSheet를 띄우는 이벤트가 적용되지않아 부자연스러움이 있네요...!
나중에 새로운 이슈를 통해 일괄적으로 적용하는게 좋을 것 같아 보이네요.
이 부분은 나중에 수정해봅시다!!

2023-11-15 12:27 UTC, gxxrxn commented on src/v1/book/BookCover.tsx
> +    <div className={`relative ${sizeClasses}`}>
생각해보니 inline 요소에 크기 속성을 주고 있었군요..🫠 `div` 태그로 수정하면 좋을 것 같아요! 감사합니다! 👍🏻

2023-11-15 12:31 UTC, minjongbaek commented on src/app/bookarchive/page.tsx
> +    </div>
@hanyugeon 확인했습니다. 다시 리뷰 부탁드려요~

2023-11-15 15:47 UTC, gxxrxn requested changes
저도 시맨틱 태그를 잘 사용하는 편은 아니지만.. 전체적으로 div 태그만을 사용해서 마크업하신 특별한 이유가 있을까요? 개인적으로는 특히나 tailwind를 사용하고 있기 때문에 적절한 컴포넌트 분리와 시맨틱한 태그를 사용하는 것이 코드 가독성을 높일 수 있는 방법 중 하나라고 생각하고 있어요! SEO를 고려해봤을 때도 `👀 이런 책들이 많이 꽂혔어요`, `🔥 인기 책장`과 같은 문구에는 heading 태그를 적용해도 좋지 않을까요??

수고많으셨습니다! 👍🏻

2023-11-15 15:47 UTC, gxxrxn commented on src/v1/bookArchive/BookArchiveForAuth.tsx
> +          </div>
p1;

1. 책을 클릭하면 책 상세 페이지로 이동해야하지 않을까요?
2. 아래 디자인처럼 이미지와 제목 사이에 1rem의 gap이 있으면 좋을 것 같아요!
<img width="418" alt="스크린샷 2023-11-16 오전 12 02 38" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/ac4ee4db-74af-48ec-b170-358c1ce11420">. 
3. 개인적으로는 도서 제목의 행간이 넓어서 가독성이 좋지 않은 것 같아요. 제목 요소에 `leading-tight` 속성을 주는건 어떨까요?
4. 드문 경우긴 하겠지만, 굉장히 긴 단어가 제목에 포함되면 레이아웃이 살짝 달라져요. 간단하게는 wrapper 요소에 `max-widht: 9rem`을 적용하면 해결할 수 있을 것 같아요!
<img width="441" alt="스크린샷 2023-11-16 오전 12 21 24" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/32911a92-cf59-4955-980b-5838535596e6">

2023-11-15 16:14 UTC, minjongbaek commented on src/v1/bookArchive/BookArchiveForAuth.tsx
> +          </div>
@gxxrxn 가장 중요한 동작을 빼먹었네요 😅 
[355857b](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/436/commits/355857b51544747494628925bbb6750127287c81) 반영해두었습니다.

2023-11-15 16:17 UTC, minjongbaek commented on src/app/bookarchive/page.tsx
> +    </div>
@gxxrxn @hanyugeon 
아 재현님이 남긴 코멘트를 이제서야 제대로 이해한 것 같아요 😅 
이전에 이야기 했을 때는 layout 에 `TopHeader` 컴포넌트를 포함하는 방향으로 작업하자고 했던 것 같아요. 이와 관련해서는 이번 주 회의 시간에 다시 이야기 해보는건 어떨까요? 👀

2023-11-15 16:27 UTC, minjongbaek commented
> 전체적으로 div 태그만을 사용해서 마크업하신 특별한 이유가 있을까요? 개인적으로는 특히나 tailwind를 사용하고 있기 때문에 적절한 컴포넌트 분리와 시맨틱한 태그를 사용하는 것이 코드 가독성을 높일 수 있는 방법 중 하나라고 생각하고 있어요! SEO를 고려해봤을 때도 👀 이런 책들이 많이 꽂혔어요, 🔥 인기 책장과 같은 문구에는 heading 태그를 적용해도 좋지 않을까요??

@gxxrxn 특별한 이유는 없고, 제가 시맨틱한 마크업에 대해 잘 알지 못해서 div 태그를 주로 사용했어요. [355857b](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/436/commits/355857b51544747494628925bbb6750127287c81) 작업을 진행하면서 의견 주신대로 heading 태그로 교체하고 책을 표현하는 요소는 list 태그를 적용해봤어요.

꼼꼼한 리뷰 덕분에 좋은 코드에 대한 고민을 다시 할 수 있었어요. 다시 리뷰 부탁드리며, 시맨틱하지 못한 마크업이 있다면 말씀해주세요!

2023-11-16 12:50 UTC, gxxrxn approved these changes
적극적으로 피드백 반영해주셔서 감사해요!! 수고 많으셨습니다~!! 👍🏻

2023-11-16 12:50 UTC, gxxrxn commented on src/ui/Base/TopHeader.tsx
> +      </h1>
너무 좋은데요?? 👍🏻

2023-11-16 15:48 UTC, hanyugeon commented
@gxxrxn 
> 그런데 문득.. layout에 TopHeader 컴포넌트가 포함되어있는게 어색한것 같기두 하네요..!! 모든 페이지에서 TopHeader가 노출되는 것이 아니기 때문에 매번 pathname을 비교해서 일부 페이지에서만 렌더링하는 것도 비효율적인 것 같다는 생각이 들어요. 혹시 이전에 이와 관련해서 이야기를 나눴던 적이 있을까요? 제가 놓친거라면 죄송해요..🥺

이전에 이야기를 나누었던 적은 없던걸로 기억해요..!

`Layout` 컴포넌트를 작성할 때 원래 `BottomNavigation`만 포함시키는것이였는데
pathname 비교를 통해 보여주는 조건이 `TopHeader`도 `BottomNavigation`과 동일하여
`TopHeader`를 추가해서 작업하게 되었습니다.. 🥺

2023-11-16 15:55 UTC, hanyugeon commented on src/v1/bookArchive/BookArchiveForAuth.tsx
> +          </div>
제가 디테일하게 보지못한 부분까지 규란님이 잘 캐치해주셨군요..! 💯 👍 🙇

2023-11-16 16:00 UTC, hanyugeon approved these changes
고생하셨습니다!! 👍

2023-11-16 16:01 UTC, minjongbaek commented
@hanyugeon 그렇다면, 일단 해당 PR 이대로 머지하고 주말에 Layout 관련해서 이야기를 나눠보면 될까요~?

2023-11-16 16:07 UTC, hanyugeon commented
@minjongbaek

저는 일단 approve를 받아놓은 상태에서 회의 이후 머지하는게 좋을 것 같아요!
(첫 페이지 작업인 만큼 신중하게 되네요 ㅎ...)
다른 리뷰어분 생각은 어떠신가요 @gxxrxn  👀

2023-11-16 16:22 UTC, gxxrxn commented
@minjongbaek @hanyugeon 

논의 후에 Layout 컴포넌트가 수정될 여지가 있을 것 같아서, 이 pr은 머지하고 새로운 이슈 생성해서 한번에 작업해도 좋을 것 같아요!

2023-11-16 16:51 UTC, merged