[#437] [독서모임] Avartar, bookGroupStatus 적용 및 typo 수정
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #438
Opened 2023-11-11 12:19 UTC by WooDaeHyun

# 구현 내용

- Avartar 컴포넌트로 변경 교체
- 공통 함수로 전환된 내용 수정 (bookGroupStatus로 변경 - 독서모임 Badge 관련)
- Placeholder -> placeholder

# 스크린샷

# pr 포인트

# Help

# 관련 이슈

- Close #437

2023-11-12 07:57 UTC, minjongbaek requested changes

2023-11-12 07:57 UTC, minjongbaek commented on src/v1/bookGroup/DetailBookGroupCard.tsx
>  type BookGroupStatus = 'before' | 'dday' | 'ongoing' | 'end';
p1;
`BookGroupStatus` 타입은 `<BookGroupStatus />` 컴포넌트와 이름이 같아서 혼란을 줄 수 있는 것 같아요. 그리고 리팩터링을 하면서 더이상 사용하지 않는 것처럼 보여요.

2023-11-14 15:44 UTC, WooDaeHyun commented on src/v1/bookGroup/DetailBookGroupCard.tsx
>  type BookGroupStatus = 'before' | 'dday' | 'ongoing' | 'end';
제가 놓친 것 같습니다! type 정의한 내용이 사용하지 않는 경우에 회색(?)으로 표시되는데 해당 type 정의는 정상적으로 표시되기에 사용중인 것으로 생각했습니다. 해당 부분 수정해서 다시 push 했습니다~ 확인 부탁드려요 @minjongbaek

2023-11-15 08:31 UTC, minjongbaek approved these changes

2023-11-16 16:37 UTC, gxxrxn approved these changes

2023-11-18 16:06 UTC, merged