style: TopNavigation 스타일 수정
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #441
Opened 2023-11-11 19:35 UTC by gxxrxn

# 구현 내용

# 스크린샷

# pr 포인트

# Help

# 관련 이슈

- Close #434

2023-11-12 08:53 UTC, minjongbaek requested changes

2023-11-12 08:53 UTC, minjongbaek commented on src/hooks/useQueryWithSuspense.ts
> +export type UseQueryOptionWithoutSuspense<
👍

2023-11-12 08:53 UTC, minjongbaek commented on src/app/group/[groupId]/page.tsx
> +          <Heading text="게시글" />
ask;
해당 페이지에서 한 번만 사용돼서 컴포넌트로 만들지 않아도 되는 요소로 보이는데 컴포넌트로 분리하신 의도가 궁금해요.

2023-11-12 08:53 UTC, minjongbaek commented on src/v1/book/BookCover.tsx
> +    <div className={`relative flex-shrink-0 ${sizeClasses}`}>
[#412](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/issues/412) PR에서 [코멘트](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/436#discussion_r1388178227)를 남겨두었는데 이번 PR엔 이미 반영이 되어있네요 😅

2023-11-12 08:53 UTC, minjongbaek commented on src/queries/group/useBookGroupQuery.ts
> +export default useBookGroupQuery;
ask;
useBookQuery 만 default 로 내보내는 이유가 있으신가요?

2023-11-12 08:53 UTC, minjongbaek commented on src/queries/group/useBookGroupQuery.ts
> +  useBookGroupQuery(groupId, data => data.title);
p2;
다른 react-query Hook 과의 일관성과 일반 커스텀 훅들과의 차별성을 주기 위해 함수명 뒤에 'Query'를 붙이는건 어떻게 생각하시나요?

2023-11-12 08:53 UTC, minjongbaek commented on next.config.js
> +      },
ask;
[#440](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/issues/440) PR의 [코멘트](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/440#discussion_r1390357641)로 이미 남겨두긴 했는데 새로 추가된 두 호스트로 부터 이미지를 받는 경우가 있는건가요?

2023-11-14 16:27 UTC, gxxrxn commented on src/app/group/[groupId]/page.tsx
> +          <Heading text="게시글" />
`CommentList` 컴포넌트 내부에 있던 요소를 페이지단으로 가져오면서 분리된 형태 그대로 사용했어요. 나중에 멤버목록 컴포넌트를 보여줄 때도 충분히 재사용할 수 있을거라고 생각해요!

2023-11-14 16:47 UTC, WooDaeHyun reviewed
코멘트 확인 부탁드려요~! 👍

2023-11-14 16:47 UTC, WooDaeHyun commented on src/v1/bookGroup/detail/BookGroupInfo.tsx
>        </span>
ask;
span 안에 span을 감싸서 작성하는 것을 일반적으로 많이 활용하나요?? 

```
<div>
  <span></span>
  <span></span>
<div>
```
방식으로 저는 작성하면 저는 구조적으로 더 파악하기 쉬울 것 같다는 생각이 들었는데 오히려 불필요한 div 요소가 추가되는 것이 더 안 좋은 방향이라고 생각하시는 걸까요?! 👀

2023-11-14 16:47 UTC, WooDaeHyun commented on src/v1/bookGroup/detail/CommentList.tsx
> +                <Name name={writer.name} />
ask;
사실 개인 생각의 차이 같은데 구조분해로 따로 분리해서 필요한 부분만 사용하지 않고 그대로 객체와 그 키들을 그대로 작성하신 이유가 오히려 더 긍정적인 측면들이 있다고 생각하시는 걸까요?! 🤗

2023-11-16 11:39 UTC, gxxrxn commented on src/v1/bookGroup/detail/BookGroupInfo.tsx
> +            <span className="text-xs text-placeholder">{bookInfo.author}</span>
네 맞아요! 😀 [잘 정리된 글](https://velog.io/@eenaree/flex-item-ellipsis#2-1-%EC%9E%90%EC%8B%9D-%EC%9A%94%EC%86%8C%EC%9D%B8-inline-%EC%9A%94%EC%86%8C%EB%A5%BC-flex-item%EC%9C%BC%EB%A1%9C-%EB%B3%80%EA%B2%BD%ED%95%9C-%EA%B2%BD%EC%9A%B0)이 있어서 공유드려요!

2023-11-16 12:37 UTC, gxxrxn commented on src/v1/bookGroup/detail/BookGroupInfo.tsx
>        </span>
`span` 태그는 인라인 요소들을 묶거나 레이아웃의 변화없이 스타일을 적용하고 싶을 때 사용하는 편이고, 여기서는 current에만 하이라이팅이 필요해서 span 태그를 안에 한번 더 사용했어요! 저도 어떤 구조가 더 올바른 방향인지는 잘 모르겠지만.. 개인적으로는 불필요한 태그를 많이 사용하다보면 뎁스가 깊어지는 일이 많아서 지양하는 편인 것 같아요. 대현님이 코멘트 남겨주신 덕분에 좀 더 고민해봤는데, `span` 보다 `p` 태그로 감싸면 더 시맨틱한 마크업이 될 것 같아서 적용해봤어요! ([b6a1fcf](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/441/commits/b6a1fcfe8a9544d1f31f4a7e36e3ab27fd920721)) 감사합니다! 👍🏻

2023-11-16 12:42 UTC, gxxrxn commented on src/v1/bookGroup/detail/CommentList.tsx
> +                <Name name={writer.name} />
여기서는 이중으로 구조분해할당을 해야하는 불편함이 있기도 하고, name과 profileImageSrc의 주체를 명확하게 하기 위해 객체로 묶어 전달받았기 때문에 구조분해할당을 하지 않았어요!

2023-11-16 14:58 UTC, minjongbaek commented on src/app/group/[groupId]/page.tsx
> +          <Heading text="게시글" />
@gxxrxn 자세한 설명 감사해요. 말씀대로 사용자 목록을 보여줄 때 재사용할 수 있겠네요..!

2023-11-16 15:01 UTC, minjongbaek commented on src/queries/group/useBookGroupQuery.ts
> +export default useBookGroupQuery;
@gxxrxn 아하..! 다른 쿼리들은 한 파일에 하나의 `useQuery` 만 사용하고 있어서 default 가 어색해보이지 않았는데 `useBookGroupQuery` 는 아래 select 쿼리들이 export 되고 있어서 이상하다고 느꼈던 것 같아요. 이대로 두셔도 괜찮을 것 같아요.

2023-11-16 15:03 UTC, minjongbaek commented on src/queries/group/useBookGroupQuery.ts
> +  useBookGroupQuery(groupId, data => data.title);
@gxxrxn select를 사용한걸 보지 못했었네요. 😅 새로운 쿼리를 호출하는 것이 아니라, 쿼리를 통해 파생된 데이터라면 규란님 의견대로 'query'를 붙일 필요가 없어보이네요 👀

2023-11-16 15:04 UTC, minjongbaek approved these changes

2023-11-16 16:30 UTC, gxxrxn commented on src/v1/bookGroup/detail/BookGroupInfo.tsx
> +          <Description content={bookGroupInfo.description} />
저도.. 눈에 밟혔어요....🫠 그런데 `bookGroupInfo`를 먼저 구조분해할당 하려면 데이터가 있음을 보장하기 위해 조건문을 써야하는데, 이 부분은 더 고민해보고 싶어서 추후 Suspense 적용하면서 가독성 좋게 수정해보겠습니다!! 🙇🏻‍♀️

2023-11-18 16:08 UTC, WooDaeHyun approved these changes
고생하셨습니당!! 👍

2023-11-18 16:58 UTC, gxxrxn commented
@minjongbaek @WooDaeHyun 

conflict 해결했어요! 다시 리뷰 부탁드립니다! 🙇🏻‍♀️

2023-11-18 17:04 UTC, WooDaeHyun submitted a review, later dismissed
conflict해결 수고하셨슴다!! 👍

2023-11-19 05:02 UTC, minjongbaek submitted a review, later dismissed

2023-11-19 05:19 UTC, gxxrxn commented
@minjongbaek @WooDaeHyun 
컨플릭트 다시 해결했어요.. 다시 한번만 리뷰 부탁드려요..🥹

2023-11-19 05:23 UTC, minjongbaek approved these changes

2023-11-23 09:53 UTC, WooDaeHyun approved these changes
예쓰~!👍

2023-11-23 09:54 UTC, merged