[#457] LikeButton 컴포넌트
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #458
Opened 2023-12-06 11:54 UTC by hanyugeon

# 구현 내용
- [x] LikeButton 구현
- [x] useBookshelfLike & useBookshelfUnlike 쿼리 함수를 useMutateBookshelfLikeQuery 쿼리 함수로 병합

# 스크린샷

# pr 포인트

# Help
- LikeButton에 hover 색깔을 추가할까 고민중입니다.

# 관련 이슈

- Close #457

2023-12-06 11:56 UTC, hanyugeon commented on src/queries/bookshelf/useMutateBookshelfLikeQuery.ts
> +}) => {
```suggestion
const useMutateBookshelfLikeQuery = (
  bookshelfId: APIBookshelfInfo['bookshelfId']
) => {
```

🤔

2023-12-06 11:59 UTC, hanyugeon commented on src/v1/base/LikeButton.tsx
> +};
comment;

Figma에 있는 LikeButton의 숫자가 Text가 아닌 Vector로 된 디자인이라
디자인대로 마크업작업이 불가능하여 어색하지 않을정도로
width, height, padding값을 일부 수정하여 마크업 하였습니다.

2023-12-11 14:59 UTC, gxxrxn requested changes
수고하셨습니다!!👍🏻 코멘트 몇개 남겼어요. 확인해주세요! 🙇🏻‍♀️

2023-12-11 14:59 UTC, gxxrxn commented on src/v1/base/LikeButton.tsx
> +};
p1;

버튼의 padding 때문에 공간이 충분하지 않아서 아이콘이 스타일링한 크기보다 작게 보여지고 있는 것 같아요. 좌우 여백도 대칭일 수 있도록 마크업을 살짝 바꿨는데, 이렇게 수정해보면 어떨까요?! `min-w`를 줘서 좋아요 수가 많아지면 자연스럽게 width가 커질 수 있도록 구현했어요! (좋아요 숫자가 늘어나는데는 어느정도 한계가 있으니 말줄임을 하는 것보다 버튼의 크기가 늘어나는 것이 자연스럽다고 생각했어요.)

- 현재 마크업
<img width="432" alt="스크린샷 2023-12-11 오후 10 56 50" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/a194efe0-9ce7-4cdb-a4c2-ab2284d33b07">

- 수정한 마크업
<img width="410" alt="스크린샷 2023-12-11 오후 11 38 50" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/a16b2d49-7b7d-4415-a929-b11af6c887a5">

```suggestion
 <button
      onClick={onClick}
      className={`${BG_COLOR_CLASS} flex h-[2.4rem] min-w-[5.2rem] items-center justify-center gap-[0.4rem] rounded-full border-[0.1rem] border-warning-800 bg-warning-800 px-[1rem]`}
    >
      <IconHeart
        className={`${ICON_COLOR_CLASS} h-[1.5rem] w-[1.5rem] fill-white stroke-[0.15rem]`}
      />
      <p
        className={`${TEXT_COLOR_CLASS} min-w-[1.5rem] text-center text-xs font-bold`}
      >
        {likeCount}
      </p>
    </button>
```

2023-12-11 14:59 UTC, gxxrxn commented on src/queries/bookshelf/useMutateBookshelfLikeQuery.ts
> +}) => {
개인적으로는 매개변수가 2개 이상이 아니라면, 객체로 감쌀 필요는 없을 것 같아요!

2023-12-11 14:59 UTC, gxxrxn commented on src/v1/base/LikeButton.tsx
> +};
p3;

정말 정말 사소한 부분이지만.. `onClick`은 옵셔널하게 선언해도 괜찮지 않을까요? 이벤트 핸들러는 원래 옵셔널하기도 하고, 확장성을 고려한다면 굳이 required 일 필요는 없을 것 같다고 생각해요!

2023-12-12 12:51 UTC, minjongbaek submitted a review, later dismissed
👍 👍 👍 규란님이 작성해주신 스타일 관련 코멘트만 확인해주시면 될 것 같아요~

2023-12-14 10:41 UTC, hanyugeon commented on src/v1/base/LikeButton.tsx
> +};
[91d3639](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/458/commits/91d363980475b209b5204ab2286877d9d5126c28)

수정하였습니다! 훨씬 좋은것 같아요!!
아이콘이 생각처럼 스타일링이 안되길래 뭐가 문제였나 싶었는데
수직 padding값 때문이였네요 👍

2023-12-14 10:42 UTC, hanyugeon commented on src/v1/base/LikeButton.tsx
> +};
반영하였습니다! [25ad6ff](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/458/commits/25ad6ff6780d2766f9aa6f253b079a5072c10034)

2023-12-14 10:42 UTC, hanyugeon commented on src/queries/bookshelf/useMutateBookshelfLikeQuery.ts
> +}) => {
반영하였습니다~ [123aa23](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/458/commits/123aa23fd951c8f8ce6fa0c9b91f698d46306650)

2023-12-14 12:48 UTC, gxxrxn approved these changes
👍🏻

2023-12-16 05:15 UTC, minjongbaek approved these changes

2023-12-18 12:31 UTC, merged