[#456] [프로필] 프로필 페이지
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #461
Opened 2023-12-09 11:18 UTC by minjongbaek

# 구현 내용

* 프로필 페이지를 새로운 디자인에 맞게 수정했어요.
* `TopHeader` 컴포넌트가 text prop을 받게끔 수정했어요.
* `TopNavigation` 컴포넌트에서 사용할 `BackButton`, `ShareButton` 컴포넌트를 구현했어요.
* 프로필 페이지에서 사용되는 쿼리 키를 리팩터링 했어요.

# 스크린샷

**내 프로필 (비로그인)**

![chrome-capture-2023-11-9](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/49975593-3e19-4569-a30c-786f1aad2196)

**내 프로필 (로그인)**

![chrome-capture-2023-11-9 (1)](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/68569510-cf4d-4e7e-b4e8-df1f0b8a823a)

**다른 사용자 프로필 (로그인)**

![chrome-capture-2023-11-9 (2)](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/8a6d2ca4-0b04-498e-850a-55e6988838e0)

# pr 포인트

* 차크라 UI를 사용하던 컴포넌트를 제거하고, 쿼리키를 리팩터링 하는 과정에서 변경된 파일의 수가 34개가 됐어요. 다음 부터는 최대한 작은 단위로 작업해보도록 할게요. 🥺 

# Help

* @hanyugeon TopNavigation을 통해 사용자 이름을 띄우게 되니 동일한 내용이 화면 2곳에서 표시되어 어색하다고 느껴져 분리해봤어요. 디자인처럼 TopNavigation에 사용자 이름을 노출하는게 좋을까요?

# 관련 이슈

- Close #456

2023-12-12 12:48 UTC, gxxrxn requested changes
수고많으셨습니다!! 👍🏻 container, presentational 패턴 첨에는 계속 파일을 타고 들어가야해서 마크업 찾기가 굉장히 복잡하다고 느껴졌는데 코드를 보다보니 각 컴포넌트의 역할이 분명해서 좋은 것 같아요! 👍🏻 코멘트 쪼끔 남겨봤는데 천천히 반영해주세요!! 🙇🏻‍♀️

2023-12-12 12:48 UTC, gxxrxn commented on src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx
> +          </Badge>
p2;

1. 굉장히 미묘한 차이지만.. `Badge size=medium` 이 아주 살짝 더 크게 스타일링 되어있더라구요.. medium으로 적용하면 디자인과 더 유사할 것 같아요! 😂 더불어 하트 아이콘의 크기를 `1.4rem`으로 살짝 키워주시면 감사하겠습니다..🤓
2. 책장 일부만 보여주는 컴포넌트에서 좋아요 뱃지는 채우지말고 아웃라인만 주자는 얘기를 나눴던 것 같아요! 그리고 `stroke-width`가 아니라 `strokeWidth` 카멜케이스를 사용해야 올바르게 적용될 것 같아요! 관련해서 console에 에러가 떠있더라구요!

```suggestion
          <Badge colorScheme="red" fontWeight="bold" size="medium" isFilled={false}>
            <div className="flex items-center gap-[0.4rem]">
              <IconHeart
                fill="#F56565"
                height="1.4rem"
                width="1.4rem"
              />
              <div className="bold text-xs">{likeCount}</div>
            </div>
          </Badge>
```

2023-12-12 12:48 UTC, gxxrxn commented on src/v1/profile/info/ProfileInfoPresenter.tsx
> +    <div className="flex flex-col gap-[2rem]">
p2;

프로필 정보와 책장/모임 UI가 구분되면 좋을 것 같아서 디자인할 때 사이에 2rem의 여백을 더 줬었어요! 코드에 반영해주시면 감사하겠습니다.. 🙏🏻

```suggestion
    <div className="flex flex-col gap-[2rem] mb-[2rem]">
```

<img width="456" alt="스크린샷 2023-12-12 오후 9 11 21" src="https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/f8a2a254-9e23-484c-8341-f1bc40b62903">

2023-12-12 12:48 UTC, gxxrxn commented on src/app/profile/me/page.tsx
> +        <div className="flex flex-col gap-[2rem]">
p2;

flex container의 역할을 하는 요소가 2개 있어요. 한개는 제거해도 괜찮지 않을까요??

2023-12-12 12:48 UTC, gxxrxn commented on src/app/profile/me/page.tsx
> +          </div>
p2;

아래 `ProfileInfoPresenter` 파일에서도 언급을 했었는데, 프로필 정보와 책장/참여한 모임 UI가 좀 더 구분될 수 있도록 2rem의 여백이 추가되면 좋을 것 같아요! 그리고 '카카오로 3초안에 가입할 수 있어요.' 텍스트의 스타일에 `text-sm`도 추가해주세요!! 🙇🏻‍♀️ 

```suggestion
          <div className="flex items-center gap-[1rem] mb-[2rem]">
            <Avatar size="large" />
            <div className="flex-grow">
              <h2 className="text-lg font-bold">로그인 / 회원가입</h2>
              <p className="text-placeholder text-sm">
                카카오로 3초만에 가입할 수 있어요.
              </p>
            </div>
            <Link href={KAKAO_LOGIN_URL}>
              <IconArrowRight width="20px" />
            </Link>
          </div>
```

2023-12-16 05:54 UTC, minjongbaek commented on src/app/profile/me/page.tsx
> +  return isAuthed() ? <MyProfileForAuth /> : <MyProfileForUnAuth />;
@gxxrxn 우선, 꼼꼼한 리뷰 감사합니다. 🙇 개발 단계에서 새로고침했을 때 hydration 에러가 발생하는지 확인해보지 못했어요. 지금 확인해보니 규란님 말씀대로 에러가 발생하네요. 의견주신대로 SSRSafeSuspense 를 사용하면 쉽게 해결할 수 있을 것 같아요 👍

2023-12-16 06:07 UTC, minjongbaek commented on src/app/profile/me/page.tsx
> +        <div className="flex flex-col gap-[2rem]">
@gxxrxn 그렇네요 👍 https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/ab5d4ae81adde9922b5f0778d5951cbb15758905

2023-12-16 06:07 UTC, minjongbaek commented on src/app/profile/me/page.tsx
> +          </div>
@gxxrxn https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/0279838b5743bdd33b56832f26a23972b5408d57

2023-12-16 06:09 UTC, minjongbaek commented on src/app/profile/me/page.tsx
>    };
@gxxrxn 좋네요! 페이지가 이동하면서 사용자게에 보여지는 미세한 깜빡거림도 없앨 수 있을 것 같아요 👍 https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/85704180373b9895234610604c366d32d6c11eb6

2023-12-16 06:10 UTC, minjongbaek commented on src/app/profile/me/page.tsx
> +  return isAuthed() ? <MyProfileForAuth /> : <MyProfileForUnAuth />;
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/85704180373b9895234610604c366d32d6c11eb6

2023-12-18 04:12 UTC, minjongbaek commented on src/v1/profile/group/ProfileGroup.tsx
>  const ProfileBookShelfSkelenton = () => {
[d3cbd35](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/d3cbd3565669f6bec2d2df0849e328aceef8578a) 👍

2023-12-18 04:12 UTC, minjongbaek commented on src/v1/profile/group/ProfileGroup.tsx
>  const ProfileBookShelfSkelenton = () => {
[d3cbd35](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/d3cbd3565669f6bec2d2df0849e328aceef8578a)

2023-12-18 04:43 UTC, minjongbaek commented on src/v1/profile/info/ProfileInfoPresenter.tsx
> +export default ProfileInfoPresenter;
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/d4b8487f4be4ced480e37d85549539683d6be92a 🙏

2023-12-18 06:46 UTC, minjongbaek commented on src/v1/profile/info/ProfileInfo.tsx
> +    </div>
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/01408a38819950687e3865849b54bc8ff2cd7d30

2023-12-18 06:47 UTC, minjongbaek commented
@gxxrxn 죄송합니다. 의견 주신 내용을 반영하는데 시간이 오래 걸렸네요. 😅 
다시 리뷰해주시면 될 것 같습니다!

2023-12-18 11:34 UTC, gxxrxn reviewed
우왓 리뷰 잘 반영해주셔서 감사해요..🙇🏻‍♀️ 코멘트 한개만 더 확인해주세요 민종님..ㅎㅎ 🙏🏻

2023-12-18 11:34 UTC, gxxrxn commented on src/app/profile/me/page.tsx
> +    <SSRSafeSuspense fallback={<Loading />}>
p2;

`<Loading fullpage/>` 이렇게 fullpage prop을 전달해서 로딩 UI가 페이지 가운데에 위치하게 하면 어떨까요..!? 로딩이 상단에 붙어있으니 잘 안보이는 것 같아서요..🙄

2023-12-18 11:34 UTC, gxxrxn commented on src/v1/profile/group/ProfileGroup.tsx
> +    </div>
comment;

`animate-pulse`를 가장 상위 요소에만 추가해도 하위 요소들에 동일한 애니메이션을 줄 수 있어요!! 😀

2023-12-19 03:56 UTC, gxxrxn submitted a review, later dismissed
👏🏻

2023-12-20 12:57 UTC, hanyugeon approved these changes
리뷰가 많이 늦었네요 고생하셨습니다!

`QueryErrorResetBoundary`를 알게되어서 좋았어요 😊

2023-12-20 12:57 UTC, hanyugeon commented on src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx
> +              />
comment;

회의내용대로 tailwind 적용하는것을 이번 pr에서 수정하는게 좋을까요
혹은 icon 스타일링 관련 코드들을 추후 이슈를 통해 일괄적으로 수정하는게 좋을까요 🤔

2023-12-20 13:01 UTC, hanyugeon commented on src/v1/profile/bookShelf/ProfileBookShelf.tsx
>  const ProfileBookShelfSkelenton = () => {
p3;

아아악 어프루브하고 오타를 발견했네요..!
Skelenton -> Skeleton

2023-12-20 13:03 UTC, hanyugeon commented on src/v1/profile/info/ProfileInfo.tsx
>  const ProfileInfoSkelenton = () => {
p3;

여기도 오타가 있습니다...!

2023-12-20 15:39 UTC, minjongbaek commented on src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx
> +              />
@hanyugeon 이번 pr 에서 수정할 수 있는 부분들은 수정하는게 좋을 것 같아서 반영해두었어요! https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/743b2eeaf10253140a5e648f7d90ab0fd8029669

2023-12-20 15:40 UTC, minjongbaek commented
@hanyugeon 꼼꼼한 리뷰 감사드려요. 오타는 수정했어요. https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/461/commits/87e723f957b21bd97e7f842633ea4cf1369c098f

다시 Approve 부탁드려요~ @gxxrxn

2023-12-20 15:41 UTC, hanyugeon approved these changes
💯

2023-12-20 15:43 UTC, gxxrxn approved these changes

2023-12-20 15:46 UTC, merged