[#455] [모임 상세] 모임 가입 문제 페이지
prgrms-web-devcourse/Team-Gaerval-Dadok-FE pull request #462
Opened 2023-12-09 17:34 UTC by gxxrxn

# 구현 내용
- 모임 가입 페이지 구현했어요.

# pr 포인트
- 모임 가입 문제가 없거나 사용자가 이미 모임의 멤버인 경우, 해당 페이지에 접근하면 not found 페이지가 렌더링돼요!

# 관련 이슈

- Close #455

2023-12-16 05:41 UTC, minjongbaek reviewed
늦어서 죄송합니다 🙏 
전체적으로 깔끔하게 작성해주셔서 리뷰하기 수월했어요. 👍
제가 남긴 `ask;` 코멘트 확인 부탁드려요!

2023-12-16 05:41 UTC, minjongbaek commented on src/v1/bookGroup/BookGroupNavigation.tsx
> +};
ask;
`children` 을 바로 렌더링 하지 않고, `getTargetChildren()` 을 통해 렌더링하는 이유는, children 요소의 위치를 정해주기 위해서인가요?

2023-12-16 05:41 UTC, minjongbaek commented on src/v1/bookGroup/BookGroupNavigation.tsx
> +const WriteButtonType = (<WriteButton />).type;
ask;
`(JSX.Element).type` 이 생소해서 console.log() 로 찍어보니 props에 대한 내용인 것 같은데 맞나요? 👀

2023-12-16 05:41 UTC, minjongbaek commented on src/hooks/group/useJoinBookGroup.ts
> +      onSuccess?.();
p5;
`onSuccess && onSuccess();` 와 동일하게 동작하는 걸까요? 만약 그렇다면 명시적으로 `onSuccess()` 를 체크하는게 읽기 편한 코드가 될 것 같다고 생각이드네요.

2023-12-16 06:34 UTC, gxxrxn commented on src/v1/bookGroup/BookGroupNavigation.tsx
> +const WriteButtonType = (<WriteButton />).type;
저도 정확히는 모르지만, 컴포넌트의 생성자 함수에 대한 정보를 담고 있는 것 같았어요. 두 컴포넌트가 동일한지를 비교하기 위해 많이 사용하는 것 같아요!

2023-12-16 06:38 UTC, gxxrxn commented on src/v1/bookGroup/BookGroupNavigation.tsx
> +};
네 맞아요!! children으로 들어올 수 있는 요소를 필터링하고, 정해진 위치에 각 요소를 배치하기 위해 사용했습니다!

2023-12-16 06:43 UTC, gxxrxn commented on src/v1/bookGroup/BookGroupNavigation.tsx
> +    >
[61478b2](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/462/commits/61478b2ea67b78e3a2327119a09219e0543abae8)

커밋 메세지를 이상하게 작성했네요..😂 같은 routeOption을 비교하는 로직이라 간단하게 삼항연산자로 작성했었는데 switch문으로 수정하니 더 보기 좋은 것 같아요!! 감사합니다! 👍🏻

2023-12-16 06:47 UTC, gxxrxn commented on src/hooks/group/useJoinBookGroup.ts
> +      onSuccess?.();
[896cf2e](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/462/commits/896cf2e04490c74d39c3523b3dcfea04df9744ab)

onSuccess가 undefined인 경우 동일하게 동작해요! 명시적으로 truthy한지 체크하도록 수정했습니다! 👍🏻

2023-12-18 03:22 UTC, minjongbaek submitted a review, later dismissed
👍 덕분에 새로운 패턴에 대해서 알 수 있었습니다~

2023-12-18 10:36 UTC, hanyugeon requested changes
고생하셨습니다
리뷰가 많이 늦었네요 😢 

코멘트 몇 개만 확인해주세요!

2023-12-18 10:36 UTC, hanyugeon commented on src/app/group/[groupId]/join/page.tsx
> +          />
p3;

```suggestion
          <Input
            {...register('answer', {
              required: '정답을 입력해주세요',
              pattern: {
                value: /^\S*$/g,
                message: '띄어쓰기 없이 정답을 입력해주세요.',
              },
              minLength: { value: 1, message: '2자 이상 입력해주세요.' },
              maxLength: { value: 10, message: '10자 이하 입력해주세요.' },
            })}
            placeholder="띄어쓰기 없이 정답을 입력해주세요"
            error={!!errors.answer}
          />
```


작성해주신 코드에는 `placeholder`로 띄어쓰기 없이 정답을 입력해주세요 라고 명시하고 있습니다.
리액트훅폼 `register`의 옵션 `pattern`과 정규표현식 `/^\S*$/g`을 활용해서
사용자로부터 띄어쓰기를 받지 않도록 강제할 수도 있을것 같아요!

2023-12-18 11:15 UTC, gxxrxn commented on src/app/group/[groupId]/join/page.tsx
> +          />
[895e489](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/462/commits/895e48995ff6abdc3df8f1dcf20e92f794bc8af4) 👍🏻

2023-12-18 11:15 UTC, gxxrxn commented on src/app/group/[groupId]/join/page.tsx
> +              minLength: { value: 1, message: '2자 이상 입력해주세요.' },
[895e489](https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/pull/462/commits/895e48995ff6abdc3df8f1dcf20e92f794bc8af4) 헉! 정답은 사실 1~10자 사이로 입력받아야해서 메세지를 수정했어요. 감사합니다! 👍🏻

2023-12-18 11:26 UTC, minjongbaek approved these changes

2023-12-18 11:27 UTC, minjongbaek approved these changes

2023-12-18 12:35 UTC, hanyugeon approved these changes
👍

2023-12-18 12:36 UTC, merged